services:
  keep-frontend:
    extends:
      file: docker-compose.common.yml
      service: keep-frontend-common
    image: us-central1-docker.pkg.dev/keephq/keep/keep-ui
    environment:
      - AUTH_TYPE=NO_AUTH
      - API_URL=http://keep-backend:8080
    volumes:
      - ./state:/state
    depends_on:
      - keep-backend

  keep-backend:
    extends:
      file: docker-compose.common.yml
      service: keep-backend-common
    image: keep-api
    environment:
      - AUTH_TYPE=NO_AUTH
      - KEEP_MEMORY_PROFILING=false
      - SCHEDULER=true
      - POSTHOG_DISABLED=true
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./state:/state

  keep-websocket-server:
    extends:
      file: docker-compose.common.yml
      service: keep-websocket-server-common
